"""edit user

Revision ID: 18f4f14f0b89
Revises: 2335288af9d9
Create Date: 2021-11-22 16:04:11.798559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f4f14f0b89'
down_revision = '2335288af9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=35), nullable=False))
    op.create_unique_constraint(None, 'user', ['fullname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
